### ISSUE TITLE
Tool window is missing on PyCharm 2022.2 

### ISSUE THREAD

**Issue by Alireza2n** [BredoGen/ProjectEnv#15]
After PyCharm 2022.2 release tool window goes missing, also version on market is 0.0.5 but latest git version is 0.1.0.

Thank you for the great plugin.

**Comment by BredoGen** [comment]
Python extension points to patch env vars are broken after 2022.2 release... Only terminal extension works. Looking for new way to implement this.

Currently the plugin is incompatible with 2022.2+.

I strongly believe these features must be implemented in Pycharm out of box. Please also vote for the feature request: https://youtrack.jetbrains.com/issue/PY-5543/Run-Configuration-Allow-environment-variables-to-load-from-env-file

**Comment by hurrycaner** [comment]
Looking forward this too, this plugin is amazing!

**Comment by BredoGen** [comment]
Thank you for contribution.

Yes, the extension point is broken in 2022.2 release. 

There is some workaround implemented in [EnvFile](https://github.com/ashald/EnvFile) but I have no enough time to update this project.

Jetbrains [promises](https://youtrack.jetbrains.com/issue/PY-5543/Run-Configuration-Allow-environment-variables-to-load-from-env-file#focus=Comments-27-6466190.0-0) to implement this feature in releases after 2022.3. Actually it's a must have feature in IDE and should be built-in. Hope we'll see this feature in 2023 release.

Currently I suggest to use EnvFile and [direnv](https://direnv.net/) to use env vars in IDE Terminal.
