### ISSUE TITLE
Incompatible: requires IDE build 221.* or earlier (2022.2)

### ISSUE THREAD

**Issue by autoferrit** [BredoGen/ProjectEnv#16]
This seems to be incompatible with the new 2022.2 version of the pycharm editor.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/89895/185971088-bacf3bca-fe96-4dd6-8a24-7a1eacf4c324.png">
<img width="332" alt="image" src="https://user-images.githubusercontent.com/89895/185971265-16f4ba24-67ef-445f-bff4-a7d52aa1d080.png">
<img width="299" alt="image" src="https://user-images.githubusercontent.com/89895/185971393-4c4cb666-dbe8-4680-87c1-f6099c31c3d3.png">

**Comment by sjawaji** [comment]
I am also holding my Goland update.  Any timeline to make it compatible?

**Comment by BredoGen** [comment]
Thank you for contribution.

Yes, the extension point is broken in 2022.2 release. 

There is some workaround implemented in [EnvFile](https://github.com/ashald/EnvFile) but I have no enough time to update this project.

Jetbrains [promises](https://youtrack.jetbrains.com/issue/PY-5543/Run-Configuration-Allow-environment-variables-to-load-from-env-file#focus=Comments-27-6466190.0-0) to implement this feature in releases after 2022.3. Actually it's a must have feature in IDE and should be built-in. Hope we'll see this feature in 2023 release.

Currently I suggest to use EnvFile and [direnv](https://direnv.net/) to use env vars in IDE Terminal.
