### ISSUE TITLE
PyCharm 2021.2 Compatability

### ISSUE THREAD

**Issue by dgarrick** [BredoGen/ProjectEnv#2]
What needs to be done to get this plugin to work with the latest versions of PyCharm? If it's not too much work, I might be able to pitch in and help.

**Comment by BredoGen** [comment]
Hi,
Just had no time to handle this. Thank you for reminder. 
Released 0.0.3 version, it's on Jetbrains review now.

**Comment by dgarrick** [comment]
Awesome, thanks!
