### ISSUE TITLE
Intellij 2022.1 Compatibility

### ISSUE THREAD

**Issue by ustieber** [BredoGen/ProjectEnv#5]
Unfortunately, the plugin stopped working since JetBrains is rolling out the 2022.1 tool versions. In my case, I'm using the plugin with Intellij. Is there a way to get a version of the plugin working with the 2022.1 version, or more general with the 2022.x version?

**Comment by BredoGen** [comment]
Hi,
Thank you for using it.

Version 0.0.5 has been released and pending JetBrains approval now. 

It's also available for manual install from GitHub Releases.

**Comment by ustieber** [comment]
Hi,
Thanks for the very quick update. Installed it from GitHub. This great plugin now works perfectly fine again.
